### ISSUE TITLE
Remove or replace componentWillReceiveProps

### ISSUE THREAD

**Issue by snailthrone** [ebuddj/ebu-init#1]
componentWillReceiveProps is considered legacy and should be avoided in new code. Will not work with React v17 and can be replaced with getDerivedStateFromProps.

https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

https://reactjs.org/docs/react-component.html#updating

https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops

**Comment by teelmo** [comment]
Fixed in 12fc2d2567d58d571315aa7c1a11b8ff701b5409
